database.drivername=com.microsoft.sqlserver.jdbc.SQLServerDriver
database.url=jdbc:sqlserver://localhost:1433;databaseName=LeonPower;encrypted=true;trustServerCertificate=true
database.username=watcher
database.pasword=P@ssw0rd